let s1 = 'sarthak';
let s2 = 'Nalage';
console.log(s1 + s2);
console.log(10 + 20 + '23');
let s3 = ('10' + 220 + 23);
console.log(typeof s3)
let s4 = 1 + 2 + 3 + ' ' + 45;
console.log(s4);
console.log(null + true + false);
console.log("" + null + true + 23 + false);
s4 = "" + null + true + 23 + false;
console.log(typeof s4);
console.log(true + 2);
console.log(true + undefined);
console.log('str' + undefined);
console.log('true' - 1);
console.log("1" - true);
console.log(true + 'true');
console.log('s'-'a');
console.log("Comparison Operator");
let r1 = true < false + 1;
console.log(r1);
console.log((true > false) + true);
console.log("Equality Operator(loose and strict)");
console.log(true == false + 1);
console.log('true' < 'APe');
console.log('10' > true);
console.log("Special Cases(bug's)");
console.log(true < undefined);
console.log(undefined == null);
let num1 = 23123434334n;
console.log(typeof num1 + 45);
let n2 = 10, n3 = 10, n4;
console.log(n4 = n2 + n3);
console.log(n4);
console.log(n4 += n2);
console.log(n4);
